package com.step2.controller;
// Generated Mar 23, 2015 11:30:57 AM by Hibernate Tools 3.2.1.GA



/**
 * Permisiondetail generated by hbm2java
 */
public class Permisiondetail  implements java.io.Serializable {


     private Integer id;
     private String profileId;
     private String nature;
     private String address;
     private String pincode;
     private Integer peopleNumber;
     private String document;
     private String processionFrom;
     private String processionTo;
     private String permisionId;

    public Permisiondetail() {
    }

    public Permisiondetail(String profileId, String nature, String address, String pincode, Integer peopleNumber, String document, String processionFrom, String processionTo, String permisionId) {
       this.profileId = profileId;
       this.nature = nature;
       this.address = address;
       this.pincode = pincode;
       this.peopleNumber = peopleNumber;
       this.document = document;
       this.processionFrom = processionFrom;
       this.processionTo = processionTo;
       this.permisionId = permisionId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getProfileId() {
        return this.profileId;
    }
    
    public void setProfileId(String profileId) {
        this.profileId = profileId;
    }
    public String getNature() {
        return this.nature;
    }
    
    public void setNature(String nature) {
        this.nature = nature;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPincode() {
        return this.pincode;
    }
    
    public void setPincode(String pincode) {
        this.pincode = pincode;
    }
    public Integer getPeopleNumber() {
        return this.peopleNumber;
    }
    
    public void setPeopleNumber(Integer peopleNumber) {
        this.peopleNumber = peopleNumber;
    }
    public String getDocument() {
        return this.document;
    }
    
    public void setDocument(String document) {
        this.document = document;
    }
    public String getProcessionFrom() {
        return this.processionFrom;
    }
    
    public void setProcessionFrom(String processionFrom) {
        this.processionFrom = processionFrom;
    }
    public String getProcessionTo() {
        return this.processionTo;
    }
    
    public void setProcessionTo(String processionTo) {
        this.processionTo = processionTo;
    }
    public String getPermisionId() {
        return this.permisionId;
    }
    
    public void setPermisionId(String permisionId) {
        this.permisionId = permisionId;
    }




}


