package com.step3.controller;
// Generated Mar 14, 2015 2:15:52 PM by Hibernate Tools 3.2.1.GA



/**
 * Datetime generated by hbm2java
 */
public class Datetime  implements java.io.Serializable {


     private Integer id;
     private String profileId;
     private String dateData;
     private String startTimeData;
     private String endTimeData;
     private String dateTimeId;

    public Datetime() {
    }

    public Datetime(String profileId, String dateData, String startTimeData, String endTimeData, String dateTimeId) {
       this.profileId = profileId;
       this.dateData = dateData;
       this.startTimeData = startTimeData;
       this.endTimeData = endTimeData;
       this.dateTimeId = dateTimeId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getProfileId() {
        return this.profileId;
    }
    
    public void setProfileId(String profileId) {
        this.profileId = profileId;
    }
    public String getDateData() {
        return this.dateData;
    }
    
    public void setDateData(String dateData) {
        this.dateData = dateData;
    }
    public String getStartTimeData() {
        return this.startTimeData;
    }
    
    public void setStartTimeData(String startTimeData) {
        this.startTimeData = startTimeData;
    }
    public String getEndTimeData() {
        return this.endTimeData;
    }
    
    public void setEndTimeData(String endTimeData) {
        this.endTimeData = endTimeData;
    }
    public String getDateTimeId() {
        return this.dateTimeId;
    }
    
    public void setDateTimeId(String dateTimeId) {
        this.dateTimeId = dateTimeId;
    }




}


