package com.paymentStatus;
// Generated Mar 25, 2015 10:39:05 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Paymentstatus generated by hbm2java
 */
public class Paymentstatus  implements java.io.Serializable {


     private Integer id;
     private String profileId;
     private Boolean paymentStatus;
     private Date dateData;

    public Paymentstatus() {
    }

    public Paymentstatus(String profileId, Boolean paymentStatus, Date dateData) {
       this.profileId = profileId;
       this.paymentStatus = paymentStatus;
       this.dateData = dateData;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getProfileId() {
        return this.profileId;
    }
    
    public void setProfileId(String profileId) {
        this.profileId = profileId;
    }
    public Boolean getPaymentStatus() {
        return this.paymentStatus;
    }
    
    public void setPaymentStatus(Boolean paymentStatus) {
        this.paymentStatus = paymentStatus;
    }
    public Date getDateData() {
        return this.dateData;
    }
    
    public void setDateData(Date dateData) {
        this.dateData = dateData;
    }




}


